# Generated by Django 2.2.7 on 2019-12-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artista.Artista')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
