# Generated by Django 2.2.7 on 2019-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='track_file',
            field=models.FileField(upload_to='Cancion'),
        ),
    ]
